# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5f28145
_src_path: ./
access: true
accountname: quickplates
appname: next-example
description: Next.js app example ⚫
docs: true
docsurl: https://quickplates.github.io/next-example
envprefix: NEXT_EXAMPLE
identity: true
imagename: apps/next-example
keyprefix: next-example
port: 3000
registry: true
releases: true
reponame: next-example
repourl: https://github.com/quickplates/next-example
